### ISSUE TITLE
能不能提供nanodet_g_768_448.trt模型？

### ISSUE THREAD

**Issue by chenzhengxi** [AcherStyx/NanoDet-TensorRT#1]
仅仅用于快速测试，能用即可
`./trt_demo -v=../../recognition.mp4 --vis=1 -c=../../config/nanodet-g-traffic.yml -m=../../model/nanodet_g_768_448.trt`

**Comment by AcherStyx** [comment]
可以试试这个TensorRT Engine模型：[Google Drive](https://drive.google.com/file/d/18IgvT4wuFlXi_ioaH1yBdfLsPrkQHR8C/view?usp=sharing)
但是TensorRT的模型是针对设备上的GPU优化过的，本人没有在不同设备上运行过同一个模型所以不确定是否兼容。
TensorRT下的模型可以通过ONNX模型导出，对应的ONNX模型也放在这里：[Google Drive](https://drive.google.com/file/d/1tWmmFb2hWN4O2DpOJdf_N5Tr1WITTfwX/view?usp=sharing)

**Comment by chenzhengxi** [comment]
` Assertion `engine != nullptr' failed`
应该是不兼容，我的环境是ubuntu1804-cuda11.1-trt7.2.3.4，那个onnx模型需要下载权限，麻烦通过下。

**Comment by chenzhengxi** [comment]
` Assertion `engine != nullptr' failed`
应该是不兼容，我的环境是ubuntu1804-cuda11.1-trt7.2.3.4，那个onnx模型需要下载权限，麻烦通过下。

**Comment by AcherStyx** [comment]
> ` Assertion `engine != nullptr' failed`
> 
> 应该是不兼容，我的环境是ubuntu1804-cuda11.1-trt7.2.3.4，那个onnx模型需要下载权限，麻烦通过下。

已更新，可以试下能不能下载

**Comment by AcherStyx** [comment]
> ` Assertion `engine != nullptr' failed`
> 应该是不兼容，我的环境是ubuntu1804-cuda11.1-trt7.2.3.4，那个onnx模型需要下载权限，麻烦通过下。

另外还有一个信息，这个assert是自己加的，engine是nullptr说明了tensorrt没有正确载入模型。但是路径错误或者模型有问题，tensorrt都是不会有任何提示的(很迷惑，无法分辨问题原因)。
还有一点是回忆起来之前有用过GPU Server上导的模型，直接拿来给另一台设备用了，是提示了不匹配可能有效率问题，但仍能运行。

**Comment by chenzhengxi** [comment]
可用，谢谢
